WindowManager:
    MainWindow:
    SecondWindow:

<MainWindow>:
    name:"main"
    Button:
        text: "Start"
        on_release:
            app.root.current = "second"
            root.manager.transition.direction = "left"

<SecondWindow>:
    name: "second"

    Button:
        text: "Go Back"
        on_release:
            app.root.current = "main"
            root.manager.transition.direction = "right"

